### ISSUE TITLE
Life span curves

### ISSUE THREAD

**Issue by FranziMe** [mpg-age-bioinformatics/shiny#11]

**Comment by FranziMe** [comment]
- [x] multiple variables (up  till 2)
- [x] plot confidence interval
- [x] color
- [x] linetype 
- [x] various models
- [x] nicely print stats on model
- [x] download plot
- [x] legend
- [x] axis
- [x] title
- [x] xlab
- [x] run it in docker

**Comment by FranziMe** [comment]
- [x] checkbox for correctly formatted table (also a way to input different interaction terms, or only interaction)
- [x] excel input

**Comment by FranziMe** [comment]
- [x] add git versioning to server.R

**Comment by FranziMe** [comment]
- [x] download report
- [x] tabs for plot settings
- [x] include more plot settings
- [x] download survival table
- [x]  for downloading select width and height

**Comment by FranziMe** [comment]
Added 2 lines and corrected one line in  [Dockerfile](https://github.com/mpg-age-bioinformatics/shiny/blob/af9fb5ad6fdabc77fd740d96f49baabc011e9b51/Dockerfile#L49)

**Comment by jorgeboucas** [comment]
@drosskopp you can pull eba84d4 and close the issue

**Comment by FranziMe** [comment]
fixing group in coxph stats output
