### ISSUE TITLE
scatterplot

### ISSUE THREAD

**Issue by jorgeboucas** [mpg-age-bioinformatics/shiny#16]

**Comment by jorgeboucas** [comment]
https://shiny.rstudio.com/articles/plot-interaction.html

https://shiny.rstudio.com/reference/shiny/1.0.1/brushedPoints.html

**Comment by jorgeboucas** [comment]
- [x] zoom
- [x] download figure (cp figure code)
- [x] download selected table
- [x] hover
- [x] lwd

**Comment by FranziMe** [comment]
hover not included but clicked points,

I have one more Idea I wanna run by you:
the option to click on the dots and display the label name next to the dot.

**Comment by FranziMe** [comment]
@drosskopp please make a pull :)

**Comment by drosskopp** [comment]
pulled
