### ISSUE TITLE
heatmap

### ISSUE THREAD

**Issue by jorgeboucas** [mpg-age-bioinformatics/shiny#2]

**Comment by jorgeboucas** [comment]
https://www.r-statistics.com/2017/03/shinyheatmaply-a-shiny-app-for-creating-interactive-cluster-heatmaps/

**Comment by FranziMe** [comment]
ready, @drosskopp  please make a pull and publish on our website

**Comment by jorgeboucas** [comment]
@FranziMe @drosskopp 
there is still an issue with generating the table - this is when it needs to save `Rplots.pdf` to the `heatmap/` folder. @drosskopp how are the write rights on the `heatmap` folder ?

**Comment by drosskopp** [comment]
solved
