### ISSUE TITLE
DAVID queries

### ISSUE THREAD

**Issue by jorgeboucas** [mpg-age-bioinformatics/shiny#4]

**Comment by jorgeboucas** [comment]
http://bioconductor.org/packages/release/bioc/vignettes/RDAVIDWebService/inst/doc/RDavidWS-vignette.pdf

**Comment by jorgeboucas** [comment]
@drosskopp you can checkout the latest commit

**Comment by drosskopp** [comment]
Done. Could you check if everything is as expected?

**Comment by jorgeboucas** [comment]
There was an issue with the link to the template file: https://github.com/mpg-age-bioinformatics/shiny/raw/master/david/genes.xlsx

Solved in 89272ef
